<?php

namespace Tests\Feature;

use Corals\Modules\Messaging\Models\Discussion;
use Corals\Modules\Messaging\Models\Message;
use Corals\Modules\Messaging\Models\Participation;
use Corals\Modules\Referral\Models\Messaging;
use Corals\User\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class MessagingTest extends TestCase
{
    use DatabaseTransactions;

    protected $messageRequest;
    protected $discussionRequest;
    protected $message;
    protected $discussion;
    protected $participation;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = User::query()->whereHas('roles', function ($query) {
            $query->where('name', 'superuser');
        })->first();

        Auth::loginUsingId($user->id);
    }

    public function test_message_view()
    {
        $response = $this->get('/messaging/discussions');

        $response->assertStatus(200)->assertViewIs('Messaging::discussions.index');

        $this->assertTrue(true);
    }

    public function test_create_message()
    {
        $response = $this->get('messaging/discussions/create');

        $response->assertStatus(200)->assertViewIs('Messaging::discussions.create_edit');

        $this->assertTrue(true);
    }

    public function test_store_messaging()
    {
        $this->discussionRequest = [
            "subject" => "test" . rand(0, 10000),
            'user_id' => 1,
            'body' => 'The lorem ipsum is a placeholder text used in publishing and graphic design.
             This filler text is a short paragraph that contains all the letters of the alphabet.
             The characters are spread out evenly so that the readers
             attention is focused on the layout of the text instead of its content',
        ];

        $response = $this->post('/messaging/discussions', $this->discussionRequest);

        $this->discussion = Discussion::query()->where('subject', $this->discussionRequest['subject'])->first();

        $response->assertDontSee('The given data was invalid')
            ->assertRedirect('/messaging/discussions');

        $discussion = $this->assertDatabaseHas('messaging_discussions', [
            "subject" => $this->discussion->subject,
        ]);

        $this->messageRequest = [
            'participable_type' => get_class(user()),
            'participable_id' => user()->id,
            'body' => 'The lorem ipsum is a placeholder text used in publishing and graphic design.
             This filler text is a short paragraph that contains all the letters of the alphabet.
             The characters are spread out evenly so that the readers
             attention is focused on the layout of the text instead of its content',
        ];

        if ($discussion) {
            $this->message = Message::query()->where('participable_id',
                $this->messageRequest['participable_id'])->first();

            $message = $this->assertDatabaseHas('messaging_messages', [
                'participable_type' => $this->message->participable_type,
                'participable_id' => $this->message->participable_id,
                'body' => $this->message->body,
                'discussion_id' => $this->message->discussion_id,
            ]);

            $this->participation = Participation::query()->where('participable_id',
                $this->messageRequest['participable_id'])->first();

            $this->assertDatabaseHas('messaging_participations', [
                'discussion_id' => $message->participation->discussion_id,
                'participable_type' => $message->participation->participable_type,
                'participable_id' => $message->participation->participable_id,
            ]);
        }
        $this->assertTrue(true);
    }
}
